### ISSUE TITLE
Percakapan berkelanjutan

### ISSUE THREAD

**Issue by ahmadkeren** [rizzlogy/bardie#3]
untuk api yang https://bard.rizzy.eu.org/ apakah ada endpoint untuk percakapan berkelanjutan?
Contoh:
Q: Kenapa air laut asin?
A: Air laut asin karena .....
Q: Apa bedanya dengan air hujan?
A: Air laut dan air hujan memeliki perbedaan ....

terima kasih

**Comment by rizzlogy** [comment]
Sayangnya api ini tidak di sediakan percakapan berkelanjutan, dan hanya mempunyai 1 request chat ke servernya

**Comment by ahmadkeren** [comment]
walah... siap bang..
